tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: AmazonAWSCloudProviderShell2G
  template_author: Quali
  template_version: 1.0.0
  template_icon: DeploymentTypes-AWS-EC2.png

description: >
  sample deployment path file

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_0.yaml

node_types:

  vendor.resource.MyDeploymentPath:
    derived_from: cloudshell.nodes.CustomDeploymentOption
    properties:
      AWS AMI Id:
        type: string
        default: ""
        description: "The AWS AMI ID to launch the instance from. The AMI should be
        accessible in the selected cloud provider's AWS region. For example :ami-6869aa05."
        tags: [ user_input ]
      Allow all Sandbox Traffic:
        type: boolean
        default: true
        description: "Whether an app should allow inbound traffic from all other apps
        in the sandbox. If set to false, access from specific apps or subnets can be
        defined by an API call."
        tags: [ user_input ]
      Instance Type:
        type: string
        default: ""
        description: "The AWS EC2 instance type. The instance type determines the CPU,
        memory and networking capacity of the instance. For example: t2.large."
        tags: [ user_input ]
      IAM Role Name:
        type: string
        default: ""
        description: "Provide the IAM role name to be used in this instance."
        tags: [ user_input ]
      Inbound Ports:
        type: string
        default: ""
        description: "Ports, protocol and source to open inbound traffic from outside
        of the sandbox. The syntax is
        port[single/range]:protocol[tcp(default)/udp]:source[cidr] with semi-colon
        separation. The default source cidr, if not specified, is any (0.0.0.0/0).
        For example: 80;443:tcp:10.0.0.0/24;200-220:udp."
        tags: [ user_input ]
      Public IP Options:
        type: string
        default: ""
        description: "Select whether to create a public IP. If the VM will be connected
        to more than one subnet, and public IP is required in at least one of them, the
        'elastic IPs' option ought to be selected."
        tags: [ user_input ]
        constraints:
          - valid_values: [ "No Public IP", "Public IP (single subnet)", "Elastic IPs" ]

    artifacts:
      icon:
        file: DeploymentTypes-AWS-EC2.png
        type: tosca.artifacts.File
